### PR TITLE
Example

### PR DESCRIPTION
**Pull request by so0k**
Example PR for Atlantis testing

### CODE REVIEW

**Comment by so0k** [comment]
atlantis plan

**Comment by so0k** [comment]
**Plan Error**
```
exit status 1: running "sh -c terraform init -no-color" in "/root/.atlantis/repos/honestbee/atlantis-example/1/default": 
Initializing modules...
- module.s3bucket
  Getting source "git@github.com:honestbee/tf-modules.git?ref=master//aws/bucket"
Error downloading modules: Error loading modules: error downloading 'ssh://git@github.com/honestbee/tf-modules.git?ref=master': /usr/bin/git exited with 128: Cloning into '.terraform/modules/675ceca60e0ccf5280f0cdc9e73d01ab'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


```

**Comment by so0k** [comment]
atlantis plan

**Comment by so0k** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_instance.web
      id:                           <computed>
      ami:                          "ami-032fb460"
      associate_public_ip_address:  <computed>
      availability_zone:            <computed>
      ebs_block_device.#:           <computed>
      ephemeral_block_device.#:     <computed>
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           <computed>
      ipv6_addresses.#:             <computed>
      key_name:                     <computed>
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      root_block_device.#:          <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tenancy:                      <computed>
      volume_tags.%:                <computed>
      vpc_security_group_ids.#:     <computed>

  + null_resource.example
      id:                           <computed>

  + module.s3bucket.aws_s3_bucket.default
      id:                           <computed>
      acceleration_status:          <computed>
      acl:                          "private"
      arn:                          <computed>
      bucket:                       "honestbee-staging-atlantis-test"
      bucket_domain_name:           <computed>
      force_destroy:                "false"
      hosted_zone_id:               <computed>
      region:                       <computed>
      request_payer:                <computed>
      tags.%:                       "3"
      tags.Name:                    "honestbee-staging-atlantis-test"
      tags.Namespace:               "honestbee"
      tags.Stage:                   "staging"
      versioning.#:                 <computed>
      website_domain:               <computed>
      website_endpoint:             <computed>

  + module.s3bucket.module.label.null_resource.default
      id:                           <computed>
      triggers.%:                   "6"
      triggers.attributes:          ""
      triggers.id:                  "honestbee-staging-atlantis-test"
      triggers.name:                "atlantis-test"
      triggers.namespace:           "honestbee"
      triggers.short_id:            "ho-stg-atl"
      triggers.stage:               "staging"
Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/atlantis-example/1/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/atlantis-example/1/default/default.tfplan"


```

* To **discard** this plan click [here](http://atlantis-3932042354-p7c6d:4141/lock?id=honestbee%252Fatlantis-example%252F.%252Fdefault).

**Comment by so0k** [comment]
atlantis plan

**Comment by so0k** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_instance.web
      id:                           <computed>
      ami:                          "ami-032fb460"
      associate_public_ip_address:  <computed>
      availability_zone:            <computed>
      ebs_block_device.#:           <computed>
      ephemeral_block_device.#:     <computed>
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           <computed>
      ipv6_addresses.#:             <computed>
      key_name:                     <computed>
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      root_block_device.#:          <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tenancy:                      <computed>
      volume_tags.%:                <computed>
      vpc_security_group_ids.#:     <computed>

  + null_resource.example
      id:                           <computed>

  + module.s3bucket.aws_s3_bucket.default
      id:                           <computed>
      acceleration_status:          <computed>
      acl:                          "private"
      arn:                          <computed>
      bucket:                       "honestbee-staging-atlantis-test"
      bucket_domain_name:           <computed>
      force_destroy:                "false"
      hosted_zone_id:               <computed>
      region:                       <computed>
      request_payer:                <computed>
      tags.%:                       "3"
      tags.Name:                    "honestbee-staging-atlantis-test"
      tags.Namespace:               "honestbee"
      tags.Stage:                   "staging"
      versioning.#:                 <computed>
      website_domain:               <computed>
      website_endpoint:             <computed>

  + module.s3bucket.module.label.null_resource.default
      id:                           <computed>
      triggers.%:                   "6"
      triggers.attributes:          ""
      triggers.id:                  "honestbee-staging-atlantis-test"
      triggers.name:                "atlantis-test"
      triggers.namespace:           "honestbee"
      triggers.short_id:            "ho-stg-atl"
      triggers.stage:               "staging"
Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/atlantis-example/1/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/atlantis-example/1/default/default.tfplan"


```

* To **discard** this plan click [here](http://atlantis-3932042354-p7c6d:4141/lock?id=honestbee%252Fatlantis-example%252F.%252Fdefault).

**Comment by so0k** [comment]
atlantis plan

**Comment by so0k** [comment]
atlantis plan

**Comment by honestbee-atlantis** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_instance.web
      id:                           <computed>
      ami:                          "ami-032fb460"
      associate_public_ip_address:  <computed>
      availability_zone:            <computed>
      ebs_block_device.#:           <computed>
      ephemeral_block_device.#:     <computed>
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           <computed>
      ipv6_addresses.#:             <computed>
      key_name:                     <computed>
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      root_block_device.#:          <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tenancy:                      <computed>
      volume_tags.%:                <computed>
      vpc_security_group_ids.#:     <computed>

  + null_resource.example
      id:                           <computed>

  + module.s3bucket.aws_s3_bucket.default
      id:                           <computed>
      acceleration_status:          <computed>
      acl:                          "private"
      arn:                          <computed>
      bucket:                       "honestbee-staging-atlantis-test"
      bucket_domain_name:           <computed>
      force_destroy:                "false"
      hosted_zone_id:               <computed>
      region:                       <computed>
      request_payer:                <computed>
      tags.%:                       "3"
      tags.Name:                    "honestbee-staging-atlantis-test"
      tags.Namespace:               "honestbee"
      tags.Stage:                   "staging"
      versioning.#:                 <computed>
      website_domain:               <computed>
      website_endpoint:             <computed>

  + module.s3bucket.module.label.null_resource.default
      id:                           <computed>
      triggers.%:                   "6"
      triggers.attributes:          ""
      triggers.id:                  "honestbee-staging-atlantis-test"
      triggers.name:                "atlantis-test"
      triggers.namespace:           "honestbee"
      triggers.short_id:            "ho-stg-atl"
      triggers.stage:               "staging"
Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/honestbee/atlantis-example/1/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/honestbee/atlantis-example/1/default/default.tfplan"


```

* To **discard** this plan click [here](http://atlantis-3932042354-hs0t3:4141/lock?id=honestbee%252Fatlantis-example%252F.%252Fdefault).

**Comment by honestbee-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- path: `honestbee/atlantis-example/.` workspace: `default`

**Pull request closed without merging**
